### PR TITLE
buildSchematic: Replace consts in name

### PR DESCRIPTION
**Pull request by holmes-g**
This allows using consts in the schematic name.

### CODE REVIEW

**Comment by BalaM314** [comment]
omg someone noticed my project!
I'm not sure this would work, as the name is itself a compiler const. This is useful when including processors with $name inside them, for example, [this one](https://github.com/BalaM314/mlog/blob/main/single_files/ResourceManager/universal.mlogx), the name in the messages automatically gets changed to the schematic name.

I think the main purpose of having consts in the name would be author and version, both of which shouldn't need any replacements themselves, so this should be fine.

I'd need to change the logic a bit though, currently it determines all the compiler consts once and replaces them once.

**Comment by holmes-g** [comment]
It works with $authors, $version, and with icon constants. If $name is used in the name field, it gets substituted one time only, with the original not-already-substituted value, so if the JSON has `"name": "foo $name bar"`, the final name of the schematic is `foo foo $name bar bar`.

**Comment by BalaM314** [comment]
What if `name` is `"Schematic $version"` and `description` is `"$name\nstuff"`? That would change `description` to `"Schematic $version\nstuff"`.

**Comment by BalaM314** [comment]
Tested, works

**Comment by BalaM314** [comment]
thank you for your contribution!

**Pull request merged**
